<?php

namespace App\Http\Controllers\Tools;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;

class ContratPretController extends Controller
{
    private array $translations = [
        'fr' => [
            'union_eu'           => 'UNION EUROPÉENNE',
            'service_justice'    => 'SERVICE DE JUSTICE ET DROITS HUMAINS',
            'tribunal'           => 'TRIBUNAL EUROPÉEN DE PREMIÈRE INSTANCE',
            'titre'              => 'CONTRAT DE PRÊT',
            'registre'           => 'REGISTRE DU TRIBUNAL',
            'coordination'       => 'Service de coordination judiciaire',
            'contrat_no'         => 'CONTRAT N°',
            'entre_soussignes'   => 'ENTRE LES SOUSSIGNÉS',
            'le_preteur'         => 'LE PRÊTEUR',
            'le_beneficiaire'    => 'LE BÉNÉFICIAIRE',
            'pays'               => 'Pays :',
            'adresse'            => 'Adresse :',
            'capacite'           => 'Capacité :',
            'client_id'          => 'Client ID :',
            'civilite'           => 'M./Mme',
            'denomme_preteur'    => 'Ci-après dénommé "Le Prêteur"',
            'denomme_emprunteur' => 'Ci-après dénommé "L\'Emprunteur"',
            'convenu'            => 'Il a été expressément convenu et arrêté ce qui suit :',
            'art1_titre'         => 'ARTICLE 1 : OBJET DU PRÊT',
            'art1_p1_a'          => 'Le Prêteur consent à l\'Emprunteur, qui accepte, un prêt d\'un montant principal de',
            'art1_p1_b'          => 'Ce prêt est régi par les dispositions légales internationales ainsi que par les présentes conditions générales et particulières.',
            'art1_p2_a'          => 'L\'Emprunteur reconnaît avoir reçu toutes les informations précontractuelles nécessaires et accepte que les fonds soient destinés à un usage personnel ou professionnel légitime dans son pays de résidence :',
            'art2_titre'         => 'ARTICLE 2 : MODALITÉS DE REMBOURSEMENT',
            'art2_intro'         => 'Ce prêt est consenti pour une durée de',
            'mois'               => 'mois',
            'ans'                => 'ans',
            'art2_suite'         => 'Le remboursement s\'effectuera par mensualités constantes selon les modalités suivantes :',
            'montant_principal'  => 'Montant principal du prêt',
            'taux_interet'       => 'Taux d\'intérêt annuel (fixe)',
            'nb_echeances'       => 'Nombre d\'échéances mensuelles',
            'mensualite'         => 'Montant de l\'échéance mensuelle',
            'art3_titre'         => 'ARTICLE 3 : CONDITIONS DE CRÉDIT',
            'art3_p1'            => 'Le prêt sera débité automatiquement du compte bancaire de l\'Emprunteur selon le mandat SEPA joint. L\'Emprunteur peut également choisir de payer par virement bancaire mensuel ou par tout autre moyen de paiement légalement admissible, en appliquant le même mode de paiement de manière cohérente.',
            'art4_titre'         => 'ARTICLE 4 : OBSERVATION ET UTILISATION DES CARTES',
            'observation'        => 'Observation :',
            'art4_p1'            => 'L\'Emprunteur s\'interdit d\'utiliser des cartes de crédit de quelque nature que ce soit (Article 1.513 du Code Civil).',
            'art4_p2'            => 'Les Parties conviennent que le délai de notification pour chaque Débit Direct est de 5 jours ouvrables avant l\'échéance du Débit Direct concerné. Ce délai de notification ne peut être modifié que moyennant accord préalable de l\'Emprunteur et du Créancier, dans le cadre d\'un modèle spécial d\'amortissement.',
            'art4_p3'            => 'La valeur des intérêts, la valeur des échéances et la durée des mensualités sont indiqués dans le tableau d\'amortissement. L\'Emprunteur doit payer les intérêts et le capital selon les modalités indiquées. Cet échéancier d\'intérêts ne peut être modifié que moyennant accord préalable spécial entre les parties.',
            'art5_titre'         => 'ARTICLE 5 : PAIEMENT ANTICIPÉ',
            'art5_p1'            => 'Toutes les sommes dues par l\'Emprunteur, en principal, intérêts et accessoires, seront payables sans aucune déduction pour quelque motif que ce soit.',
            'art5_p2'            => 'Sans préjudice de toute action en justice par l\'Emprunteur pour non-respect de quelque engagement que ce soit par le Créancier, celui-ci pourra exiger le paiement intégral du capital restant dû en cas de :',
            'art5_li1'           => 'Non-respect par l\'Emprunteur de l\'une quelconque de ses obligations (notamment en cas de défaillance, suspension de paiements, ou tout autre événement pouvant affecter le patrimoine de l\'Emprunteur),',
            'art5_li2'           => 'Refus, aliénation ou toute autre disposition du Créancier susceptible d\'anticiper ou d\'empêcher le remboursement du prêt,',
            'art5_li3'           => 'Tentative de l\'Emprunteur d\'obtenir ou d\'exécuter le contrat par quelque moyen illégal, comme la cession, la sous-location ou autre.',
            'art6_titre'         => 'ARTICLE 6 : ATTRIBUTION DES RESPONSABILITÉS ET JURIDICTION',
            'art6_p1'            => 'Le présent contrat est régi par les principes du droit international des contrats et les conventions européennes applicables en matière de crédit. Les parties reconnaissent la nature internationale de cette transaction financière.',
            'art6_p2'            => 'En cas de litige relatif à la validité, l\'interprétation ou l\'exécution du présent contrat, les parties conviennent de privilégier en premier lieu la médiation et la conciliation amiable.',
            'art6_p3'            => 'À défaut d\'accord amiable, tout différend sera soumis à la juridiction compétente du pays de résidence de l\'Emprunteur, conformément aux règles de compétence territoriale en vigueur. L\'Emprunteur bénéficie ainsi de la protection juridictionnelle de son domicile légal.',
            'art7_titre'         => 'ARTICLE 7 : REMBOURSEMENT ANTICIPÉ',
            'art7_p1'            => 'Les paiements seront effectués mensuellement. Les Mensualités de remboursement calculées à tout moment, total ou partiel, ne peuvent être remboursées avant l\'échéance.',
            'art7_p2'            => 'En cas de remboursement anticipé, l\'Emprunteur doit rembourser au Créancier exactement les dépenses occasionnées par ce désistement.',
            'art7_partiel'       => 'Remboursement anticipé partiel :',
            'art7_p3'            => 'Les Mensualités de remboursement et le solde devront être recalculés à 5% de la valeur du prêt, sauf en cas de solde débiteur. Dans ce cas, la garantie sera également réduite en conséquence, sans que le montant restant dû ne puisse excéder 0,2 points de pourcentage du capital restant dû avant le remboursement.',
            'art8_titre'         => 'ARTICLE 8 : RETARDS DE PAIEMENT',
            'art8_p1'            => 'En cas de non-respect du principal, des intérêts et des accessoires ou d\'une fraction des amortissements non remboursés à temps, l\'Emprunteur sera tenu de payer une pénalité de 0,2 points de pourcentage du capital du prêt, augmentée de 0,2 points de pourcentage, sans préjudice.',
            'art8_p2'            => 'Cette pénalité augmentée sera également appliquée aux intérêts, lorsque des intérêts débiteurs sont exigibles conformément aux termes de l\'Article 1.108 du Code Civil. Cette stipulation d\'intérêts ne peut préjudicier au Créancier qui pourra anticiper le remboursement conformément aux conditions prévues dans le présent document et, en conséquence, exiger le remboursement de la totalité du capital restant dû.',
            'art8_p3'            => 'La première échéance du prêt mensuel sera payée trois mois après réception des fonds sur le compte bancaire, entre les 5 et 7 de chaque mois.',
            'art8_p4'            => 'En tout état de cause, l\'Emprunteur doit rembourser au Créancier le montant total ou partiel des paiements effectués à 5% de la valeur du prêt, excluant le cas du solde débiteur. Dans ces cas, les paiements couvriront une taxe compensatoire qui sera égale aux intérêts du capital restant dû avant le remboursement.',
            'art9_titre'         => 'ARTICLE 9 : GARANTIE D\'ACTIVATION ET ENGAGEMENT',
            'art9_p1'            => 'Il est expressément convenu que le Prêteur ou l\'institution bancaire partenaire peut exiger de l\'Emprunteur le versement anticipé d\'une somme équivalente à une (1) jusqu\'à trois (3) mensualités du prêt. Ce versement est destiné à servir de garantie d\'activation technique des flux de transfert externes et de preuve d\'engagement de bonne foi de l\'Emprunteur. Cette somme sera intégralement créditée au bénéfice de l\'Emprunteur et déduite des échéances futures du prêt, réduisant ainsi le nombre total de mensualités restant dues.',
            'art10_titre'        => 'ARTICLE 10 : DÉCLARATION ET SIGNATURE',
            'art10_p1'           => 'En signant ci-dessous et en haut de chaque page, les parties de l\'accord s\'engagent à respecter et à atteindre les termes et les termes de cet accord.',
            'art10_p2'           => 'Les parties de l\'accord reconnaissent avoir reçu et lu cet Accord. Les parties déclarent avoir reçu et lu le présent contrat, soumettant les annexes qui en font partie.',
            'lemprunteur'        => 'L\'Emprunteur :',
            'beneficiaire_legal' => 'Bénéficiaire légal du prêt',
            'fait_a'             => 'Fait à',
            'le'                 => 'le',
            'le_preteur_represente' => 'Le Prêteur représenté par :',
            'important'          => 'IMPORTANT : CE CONTRAT DOIT ÊTRE IMPRIMÉ, DATÉ ET SIGNÉ PAR L\'EMPRUNTEUR AFIN DE DÉCLENCHER LE VIREMENT DES FONDS SUR LE COMPTE BANCAIRE DÉSIGNÉ.',
        ],
        'en' => [
            'union_eu'           => 'EUROPEAN UNION',
            'service_justice'    => 'JUSTICE AND HUMAN RIGHTS SERVICE',
            'tribunal'           => 'EUROPEAN COURT OF FIRST INSTANCE',
            'titre'              => 'LOAN AGREEMENT',
            'registre'           => 'COURT REGISTRY',
            'coordination'       => 'Judicial Coordination Service',
            'contrat_no'         => 'CONTRACT N°',
            'entre_soussignes'   => 'BETWEEN THE UNDERSIGNED',
            'le_preteur'         => 'THE LENDER',
            'le_beneficiaire'    => 'THE BORROWER',
            'pays'               => 'Country:',
            'adresse'            => 'Address:',
            'capacite'           => 'Capacity:',
            'client_id'          => 'Client ID:',
            'civilite'           => 'Mr./Ms.',
            'denomme_preteur'    => 'Hereinafter referred to as "The Lender"',
            'denomme_emprunteur' => 'Hereinafter referred to as "The Borrower"',
            'convenu'            => 'It has been expressly agreed and decided as follows:',
            'art1_titre'         => 'ARTICLE 1: SUBJECT OF THE LOAN',
            'art1_p1_a'          => 'The Lender agrees to grant the Borrower a loan in the principal amount of',
            'art1_p1_b'          => 'This loan is governed by international legal provisions as well as these general and specific terms and conditions.',
            'art1_p2_a'          => 'The Borrower acknowledges having received all necessary pre-contractual information and agrees that the funds are intended for legitimate personal or professional use in their country of residence:',
            'art2_titre'         => 'ARTICLE 2: REPAYMENT TERMS',
            'art2_intro'         => 'This loan is granted for a period of',
            'mois'               => 'months',
            'ans'                => 'years',
            'art2_suite'         => 'Repayment will be made in constant monthly installments as follows:',
            'montant_principal'  => 'Principal loan amount',
            'taux_interet'       => 'Annual interest rate (fixed)',
            'nb_echeances'       => 'Number of monthly installments',
            'mensualite'         => 'Monthly installment amount',
            'art3_titre'         => 'ARTICLE 3: CREDIT CONDITIONS',
            'art3_p1'            => 'The loan will be automatically debited from the Borrower\'s bank account under the attached SEPA mandate. The Borrower may also choose to pay by monthly bank transfer or any other legally admissible payment method, applying the same payment method consistently.',
            'art4_titre'         => 'ARTICLE 4: OBSERVATION AND USE OF CARDS',
            'observation'        => 'Observation:',
            'art4_p1'            => 'The Borrower is prohibited from using credit cards of any kind (Article 1.513 of the Civil Code).',
            'art4_p2'            => 'The Parties agree that the notification period for each Direct Debit is 5 business days before the due date of the relevant Direct Debit. This notification period can only be changed with the prior agreement of the Borrower and the Creditor, within the framework of a special amortization model.',
            'art4_p3'            => 'The interest value, installment value, and duration of monthly payments are indicated in the amortization table. The Borrower must pay interest and principal as indicated. This interest schedule can only be changed with special prior agreement between the parties.',
            'art5_titre'         => 'ARTICLE 5: EARLY PAYMENT',
            'art5_p1'            => 'All amounts owed by the Borrower, in principal, interest, and accessories, will be payable without any deduction for any reason whatsoever.',
            'art5_p2'            => 'Without prejudice to any legal action by the Borrower for non-compliance with any commitment by the Creditor, the Creditor may demand full payment of the outstanding capital in case of:',
            'art5_li1'           => 'Non-compliance by the Borrower with any of their obligations (particularly in case of default, suspension of payments, or any other event that may affect the Borrower\'s assets),',
            'art5_li2'           => 'Refusal, alienation or any other action by the Creditor likely to anticipate or prevent repayment of the loan,',
            'art5_li3'           => 'Attempt by the Borrower to obtain or execute the contract by any illegal means, such as assignment, subletting, or otherwise.',
            'art6_titre'         => 'ARTICLE 6: ATTRIBUTION OF RESPONSIBILITIES AND JURISDICTION',
            'art6_p1'            => 'This contract is governed by the principles of international contract law and applicable European conventions on credit. The parties acknowledge the international nature of this financial transaction.',
            'art6_p2'            => 'In case of dispute concerning the validity, interpretation or performance of this contract, the parties agree to first prioritize mediation and amicable conciliation.',
            'art6_p3'            => 'Failing amicable agreement, any dispute shall be submitted to the competent court in the Borrower\'s country of residence, in accordance with applicable territorial jurisdiction rules. The Borrower thus benefits from the legal protection of their legal domicile.',
            'art7_titre'         => 'ARTICLE 7: EARLY REPAYMENT',
            'art7_p1'            => 'Payments will be made monthly. The repayment installments calculated at any time, total or partial, cannot be repaid before maturity.',
            'art7_p2'            => 'In case of early repayment, the Borrower must reimburse the Creditor exactly for the expenses caused by this withdrawal.',
            'art7_partiel'       => 'Partial early repayment:',
            'art7_p3'            => 'The repayment installments and balance shall be recalculated at 5% of the loan value, except in case of debit balance. In this case, the guarantee will also be reduced accordingly, without the outstanding amount exceeding 0.2 percentage points of the outstanding capital before repayment.',
            'art8_titre'         => 'ARTICLE 8: LATE PAYMENTS',
            'art8_p1'            => 'In case of non-compliance with the principal, interest and accessories or a fraction of the amortizations not repaid on time, the Borrower will be required to pay a penalty of 0.2 percentage points of the loan capital, increased by 0.2 percentage points, without prejudice.',
            'art8_p2'            => 'This increased penalty will also be applied to interest, when debit interest is due in accordance with Article 1.108 of the Civil Code. This interest stipulation cannot prejudice the Creditor who may anticipate repayment in accordance with the conditions provided in this document and, consequently, demand repayment of the total outstanding capital.',
            'art8_p3'            => 'The first monthly loan installment will be paid three months after receipt of funds in the bank account, between the 5th and 7th of each month.',
            'art8_p4'            => 'In any case, the Borrower must reimburse the Creditor the total or partial amount of payments made at 5% of the loan value, excluding the case of debit balance. In these cases, the payments will cover a compensatory tax equal to the interest on the outstanding capital before repayment.',
            'art9_titre'         => 'ARTICLE 9: ACTIVATION GUARANTEE AND COMMITMENT',
            'art9_p1'            => 'It is expressly agreed that the Lender or partner banking institution may require the Borrower to make an advance payment of an amount equivalent to one (1) to three (3) monthly loan installments. This payment is intended to serve as a technical activation guarantee for external transfer flows and proof of the Borrower\'s good faith commitment. This sum will be fully credited to the Borrower\'s benefit and deducted from future loan installments, thus reducing the total number of remaining monthly payments.',
            'art10_titre'        => 'ARTICLE 10: DECLARATION AND SIGNATURE',
            'art10_p1'           => 'By signing below and at the top of each page, the parties to the agreement commit to respecting and achieving the terms of this agreement.',
            'art10_p2'           => 'The parties to the agreement acknowledge having received and read this Agreement. The parties declare having received and read this contract, submitting the annexes that form part of it.',
            'lemprunteur'        => 'The Borrower:',
            'beneficiaire_legal' => 'Legal beneficiary of the loan',
            'fait_a'             => 'Done in',
            'le'                 => 'on',
            'le_preteur_represente' => 'The Lender represented by:',
            'important'          => 'IMPORTANT: THIS CONTRACT MUST BE PRINTED, DATED AND SIGNED BY THE BORROWER IN ORDER TO TRIGGER THE TRANSFER OF FUNDS TO THE DESIGNATED BANK ACCOUNT.',
        ],
        'es' => [
            'union_eu'           => 'UNIÓN EUROPEA',
            'service_justice'    => 'SERVICIO DE JUSTICIA Y DERECHOS HUMANOS',
            'tribunal'           => 'TRIBUNAL EUROPEO DE PRIMERA INSTANCIA',
            'titre'              => 'CONTRATO DE PRÉSTAMO',
            'registre'           => 'REGISTRO DEL TRIBUNAL',
            'coordination'       => 'Servicio de Coordinación Judicial',
            'contrat_no'         => 'CONTRATO N°',
            'entre_soussignes'   => 'ENTRE LOS ABAJO FIRMANTES',
            'le_preteur'         => 'EL PRESTAMISTA',
            'le_beneficiaire'    => 'EL BENEFICIARIO',
            'pays'               => 'País:',
            'adresse'            => 'Dirección:',
            'capacite'           => 'Capacidad:',
            'client_id'          => 'ID Cliente:',
            'civilite'           => 'Sr./Sra.',
            'denomme_preteur'    => 'En adelante denominado "El Prestamista"',
            'denomme_emprunteur' => 'En adelante denominado "El Prestatario"',
            'convenu'            => 'Se ha convenido y acordado expresamente lo siguiente:',
            'art1_titre'         => 'ARTÍCULO 1: OBJETO DEL PRÉSTAMO',
            'art1_p1_a'          => 'El Prestamista otorga al Prestatario un préstamo por un importe principal de',
            'art1_p1_b'          => 'Este préstamo se rige por las disposiciones legales internacionales y por las presentes condiciones generales y particulares.',
            'art1_p2_a'          => 'El Prestatario reconoce haber recibido toda la información precontractual necesaria y acepta que los fondos están destinados a uso personal o profesional legítimo en su país de residencia:',
            'art2_titre'         => 'ARTÍCULO 2: MODALIDADES DE REEMBOLSO',
            'art2_intro'         => 'Este préstamo se concede por un período de',
            'mois'               => 'meses',
            'ans'                => 'años',
            'art2_suite'         => 'El reembolso se efectuará mediante cuotas mensuales constantes según las siguientes modalidades:',
            'montant_principal'  => 'Importe principal del préstamo',
            'taux_interet'       => 'Tasa de interés anual (fija)',
            'nb_echeances'       => 'Número de cuotas mensuales',
            'mensualite'         => 'Importe de la cuota mensual',
            'art3_titre'         => 'ARTÍCULO 3: CONDICIONES DE CRÉDITO',
            'art3_p1'            => 'El préstamo se debitará automáticamente de la cuenta bancaria del Prestatario según el mandato SEPA adjunto. El Prestatario también puede optar por pagar mediante transferencia bancaria mensual o cualquier otro medio de pago legalmente admisible, aplicando el mismo método de pago de forma coherente.',
            'art4_titre'         => 'ARTÍCULO 4: OBSERVACIÓN Y USO DE TARJETAS',
            'observation'        => 'Observación:',
            'art4_p1'            => 'El Prestatario se prohíbe usar tarjetas de crédito de cualquier naturaleza (Artículo 1.513 del Código Civil).',
            'art4_p2'            => 'Las Partes acuerdan que el plazo de notificación para cada Débito Directo es de 5 días hábiles antes del vencimiento del Débito Directo correspondiente.',
            'art4_p3'            => 'El valor de los intereses, el valor de las cuotas y la duración de los pagos mensuales se indican en el cuadro de amortización.',
            'art5_titre'         => 'ARTÍCULO 5: PAGO ANTICIPADO',
            'art5_p1'            => 'Todas las sumas adeudadas por el Prestatario, en principal, intereses y accesorios, serán pagaderas sin deducción alguna por ningún motivo.',
            'art5_p2'            => 'Sin perjuicio de cualquier acción legal del Prestatario por incumplimiento de cualquier compromiso por parte del Acreedor, este podrá exigir el pago íntegro del capital pendiente en caso de:',
            'art5_li1'           => 'Incumplimiento por el Prestatario de cualquiera de sus obligaciones,',
            'art5_li2'           => 'Rechazo, enajenación u otra disposición del Acreedor susceptible de anticipar o impedir el reembolso del préstamo,',
            'art5_li3'           => 'Intento del Prestatario de obtener o ejecutar el contrato por medios ilegales.',
            'art6_titre'         => 'ARTÍCULO 6: ATRIBUCIÓN DE RESPONSABILIDADES Y JURISDICCIÓN',
            'art6_p1'            => 'El presente contrato se rige por los principios del derecho internacional de contratos y los convenios europeos aplicables en materia de crédito.',
            'art6_p2'            => 'En caso de litigio relativo a la validez, interpretación o ejecución del presente contrato, las partes acuerdan privilegiar en primer lugar la mediación y la conciliación amistosa.',
            'art6_p3'            => 'A falta de acuerdo amistoso, cualquier disputa se someterá a la jurisdicción competente del país de residencia del Prestatario.',
            'art7_titre'         => 'ARTÍCULO 7: REEMBOLSO ANTICIPADO',
            'art7_p1'            => 'Los pagos se efectuarán mensualmente. Las cuotas de reembolso calculadas en cualquier momento, total o parcialmente, no pueden reembolsarse antes del vencimiento.',
            'art7_p2'            => 'En caso de reembolso anticipado, el Prestatario debe reembolsar al Acreedor exactamente los gastos ocasionados por este desistimiento.',
            'art7_partiel'       => 'Reembolso anticipado parcial:',
            'art7_p3'            => 'Las cuotas de reembolso y el saldo deberán recalcularse al 5% del valor del préstamo.',
            'art8_titre'         => 'ARTÍCULO 8: RETRASOS DE PAGO',
            'art8_p1'            => 'En caso de incumplimiento del principal, intereses y accesorios, el Prestatario estará obligado a pagar una penalización del 0,2% del capital del préstamo.',
            'art8_p2'            => 'Esta penalización también se aplicará a los intereses, según el Artículo 1.108 del Código Civil.',
            'art8_p3'            => 'La primera cuota mensual se pagará tres meses después de la recepción de los fondos en la cuenta bancaria.',
            'art8_p4'            => 'En todo caso, el Prestatario debe reembolsar al Acreedor el importe total o parcial de los pagos efectuados al 5% del valor del préstamo.',
            'art9_titre'         => 'ARTÍCULO 9: GARANTÍA DE ACTIVACIÓN Y COMPROMISO',
            'art9_p1'            => 'Se acuerda expresamente que el Prestamista o la institución bancaria asociada puede exigir al Prestatario el pago anticipado de una cantidad equivalente a una (1) hasta tres (3) cuotas mensuales del préstamo como garantía de activación.',
            'art10_titre'        => 'ARTÍCULO 10: DECLARACIÓN Y FIRMA',
            'art10_p1'           => 'Al firmar a continuación y en la parte superior de cada página, las partes del acuerdo se comprometen a respetar los términos de este acuerdo.',
            'art10_p2'           => 'Las partes del acuerdo reconocen haber recibido y leído este Acuerdo.',
            'lemprunteur'        => 'El Prestatario:',
            'beneficiaire_legal' => 'Beneficiario legal del préstamo',
            'fait_a'             => 'Hecho en',
            'le'                 => 'el',
            'le_preteur_represente' => 'El Prestamista representado por:',
            'important'          => 'IMPORTANTE: ESTE CONTRATO DEBE SER IMPRESO, FECHADO Y FIRMADO POR EL PRESTATARIO PARA ACTIVAR LA TRANSFERENCIA DE FONDOS A LA CUENTA BANCARIA DESIGNADA.',
        ],
        'pt' => [
            'union_eu'           => 'UNIÃO EUROPEIA',
            'service_justice'    => 'SERVIÇO DE JUSTIÇA E DIREITOS HUMANOS',
            'tribunal'           => 'TRIBUNAL EUROPEU DE PRIMEIRA INSTÂNCIA',
            'titre'              => 'CONTRATO DE EMPRÉSTIMO',
            'registre'           => 'REGISTO DO TRIBUNAL',
            'coordination'       => 'Serviço de Coordenação Judicial',
            'contrat_no'         => 'CONTRATO N°',
            'entre_soussignes'   => 'ENTRE OS ABAIXO ASSINADOS',
            'le_preteur'         => 'O MUTUANTE',
            'le_beneficiaire'    => 'O MUTUÁRIO',
            'pays'               => 'País:',
            'adresse'            => 'Endereço:',
            'capacite'           => 'Capacidade:',
            'client_id'          => 'ID Cliente:',
            'civilite'           => 'Sr./Sra.',
            'denomme_preteur'    => 'Doravante denominado "O Mutuante"',
            'denomme_emprunteur' => 'Doravante denominado "O Mutuário"',
            'convenu'            => 'Foi expressamente acordado e decidido o seguinte:',
            'art1_titre'         => 'ARTIGO 1: OBJETO DO EMPRÉSTIMO',
            'art1_p1_a'          => 'O Mutuante concede ao Mutuário um empréstimo no valor principal de',
            'art1_p1_b'          => 'Este empréstimo é regido pelas disposições legais internacionais e pelas presentes condições gerais e particulares.',
            'art1_p2_a'          => 'O Mutuário reconhece ter recebido todas as informações pré-contratuais necessárias e aceita que os fundos se destinam a uso pessoal ou profissional legítimo no seu país de residência:',
            'art2_titre'         => 'ARTIGO 2: MODALIDADES DE REEMBOLSO',
            'art2_intro'         => 'Este empréstimo é concedido por um período de',
            'mois'               => 'meses',
            'ans'                => 'anos',
            'art2_suite'         => 'O reembolso será efectuado em prestações mensais constantes da seguinte forma:',
            'montant_principal'  => 'Montante principal do empréstimo',
            'taux_interet'       => 'Taxa de juro anual (fixa)',
            'nb_echeances'       => 'Número de prestações mensais',
            'mensualite'         => 'Montante da prestação mensal',
            'art3_titre'         => 'ARTIGO 3: CONDIÇÕES DE CRÉDITO',
            'art3_p1'            => 'O empréstimo será debitado automaticamente da conta bancária do Mutuário conforme o mandato SEPA anexo.',
            'art4_titre'         => 'ARTIGO 4: OBSERVAÇÃO E UTILIZAÇÃO DE CARTÕES',
            'observation'        => 'Observação:',
            'art4_p1'            => 'O Mutuário proíbe-se de utilizar cartões de crédito de qualquer natureza (Artigo 1.513 do Código Civil).',
            'art4_p2'            => 'As Partes acordam que o prazo de notificação para cada Débito Directo é de 5 dias úteis antes do vencimento.',
            'art4_p3'            => 'O valor dos juros, das prestações e a duração dos pagamentos mensais são indicados no quadro de amortização.',
            'art5_titre'         => 'ARTIGO 5: PAGAMENTO ANTECIPADO',
            'art5_p1'            => 'Todas as quantias devidas pelo Mutuário, em capital, juros e acessórios, serão pagáveis sem qualquer dedução.',
            'art5_p2'            => 'O Credor poderá exigir o pagamento integral do capital em dívida em caso de:',
            'art5_li1'           => 'Incumprimento pelo Mutuário de qualquer das suas obrigações,',
            'art5_li2'           => 'Recusa ou alienação pelo Credor susceptível de antecipar ou impedir o reembolso do empréstimo,',
            'art5_li3'           => 'Tentativa do Mutuário de obter ou executar o contrato por meios ilegais.',
            'art6_titre'         => 'ARTIGO 6: ATRIBUIÇÃO DE RESPONSABILIDADES E JURISDIÇÃO',
            'art6_p1'            => 'O presente contrato é regido pelos princípios do direito internacional dos contratos e pelas convenções europeias aplicáveis em matéria de crédito.',
            'art6_p2'            => 'Em caso de litígio, as partes acordam privilegiar a mediação e a conciliação amigável.',
            'art6_p3'            => 'Na falta de acordo amigável, qualquer litígio será submetido à jurisdição competente do país de residência do Mutuário.',
            'art7_titre'         => 'ARTIGO 7: REEMBOLSO ANTECIPADO',
            'art7_p1'            => 'Os pagamentos serão efectuados mensalmente. As prestações não podem ser reembolsadas antes do vencimento.',
            'art7_p2'            => 'Em caso de reembolso antecipado, o Mutuário deve reembolsar ao Credor as despesas ocasionadas.',
            'art7_partiel'       => 'Reembolso antecipado parcial:',
            'art7_p3'            => 'As prestações e o saldo deverão ser recalculados a 5% do valor do empréstimo.',
            'art8_titre'         => 'ARTIGO 8: ATRASOS DE PAGAMENTO',
            'art8_p1'            => 'Em caso de incumprimento, o Mutuário pagará uma penalização de 0,2% do capital do empréstimo.',
            'art8_p2'            => 'Esta penalização também se aplicará aos juros conforme o Artigo 1.108 do Código Civil.',
            'art8_p3'            => 'A primeira prestação mensal será paga três meses após a recepção dos fundos.',
            'art8_p4'            => 'Em qualquer caso, o Mutuário deve reembolsar ao Credor os pagamentos efectuados a 5% do valor do empréstimo.',
            'art9_titre'         => 'ARTIGO 9: GARANTIA DE ACTIVAÇÃO E COMPROMISSO',
            'art9_p1'            => 'O Mutuante pode exigir do Mutuário o pagamento antecipado de uma quantia equivalente a uma (1) a três (3) prestações mensais como garantia de activação.',
            'art10_titre'        => 'ARTIGO 10: DECLARAÇÃO E ASSINATURA',
            'art10_p1'           => 'Ao assinar abaixo, as partes comprometem-se a respeitar os termos deste acordo.',
            'art10_p2'           => 'As partes reconhecem ter recebido e lido este Acordo.',
            'lemprunteur'        => 'O Mutuário:',
            'beneficiaire_legal' => 'Beneficiário legal do empréstimo',
            'fait_a'             => 'Feito em',
            'le'                 => 'a',
            'le_preteur_represente' => 'O Mutuante representado por:',
            'important'          => 'IMPORTANTE: ESTE CONTRATO DEVE SER IMPRESSO, DATADO E ASSINADO PELO MUTUÁRIO PARA ACTIVAR A TRANSFERÊNCIA DE FUNDOS PARA A CONTA BANCÁRIA DESIGNADA.',
        ],
    ];

    private array $currencies = [
        'EUR' => ['symbol' => '€',  'name' => 'Euro'],
        'USD' => ['symbol' => '$',  'name' => 'Dollar américain'],
        'GBP' => ['symbol' => '£',  'name' => 'Livre sterling'],
        'CHF' => ['symbol' => 'Fr', 'name' => 'Franc suisse'],
        'CAD' => ['symbol' => 'CA$','name' => 'Dollar canadien'],
        'XOF' => ['symbol' => 'F',  'name' => 'Franc CFA Ouest'],
        'MAD' => ['symbol' => 'د.م.','name' => 'Dirham marocain'],
        'TND' => ['symbol' => 'DT', 'name' => 'Dinar tunisien'],
        'DZD' => ['symbol' => 'DA', 'name' => 'Dinar algérien'],
    ];

    public function index()
    {
        return view('tools.contrat-pret', [
            'currencies' => $this->currencies,
        ]);
    }

    public function generate(Request $request)
    {
        $request->validate([
            'emprunteur_nom'    => 'required|string|max:100',
            'emprunteur_pays'   => 'required|string|max:60',
            'emprunteur_id'     => 'nullable|string|max:50',
            'preteur_nom'       => 'required|string|max:100',
            'preteur_pays'      => 'required|string|max:60',
            'preteur_adresse'   => 'required|string|max:200',
            'preteur_id'        => 'required|string|max:50',
            'preteur_capacite'  => 'required|string|max:80',
            'montant'           => 'required|numeric|min:1',
            'devise'            => 'required|string|in:EUR,USD,GBP,CHF,CAD,XOF,MAD,TND,DZD',
            'taux'              => 'required|numeric|min:0|max:100',
            'duree'             => 'required|integer|min:1|max:360',
            'lang'              => 'required|string|in:fr,en,es,pt',
        ]);

        $lang      = $request->lang;
        $devise    = $request->devise;
        $t         = $this->translations[$lang] ?? $this->translations['fr'];
        $deviseSymbole = $this->currencies[$devise]['symbol'] ?? '€';
        $contractNo = strtoupper(substr($request->emprunteur_nom, 0, 3)) . '-' . date('Y') . '-' . rand(1000, 9999);

        $pdf = Pdf::loadView('tools.contrat-pret-pdf', [
            'lang'              => $lang,
            't'                 => $t,
            'contractNo'        => $contractNo,
            'emprunteurNom'     => $request->emprunteur_nom,
            'emprunteurPays'    => $request->emprunteur_pays,
            'emprunteurId'      => $request->emprunteur_id,
            'preteurNom'        => $request->preteur_nom,
            'preteurPays'       => $request->preteur_pays,
            'preteurAdresse'    => $request->preteur_adresse,
            'preteurId'         => $request->preteur_id,
            'preteurCapacite'   => $request->preteur_capacite,
            'montant'           => (float) $request->montant,
            'devise'            => $devise,
            'deviseSymbole'     => $deviseSymbole,
            'taux'              => (float) $request->taux,
            'duree'             => (int) $request->duree,
        ])->setPaper('a4', 'portrait');

        $filename = 'contrat-pret-' . strtolower(str_replace(' ', '-', $request->emprunteur_nom)) . '-' . date('Ymd') . '.pdf';

        return $pdf->download($filename);
    }
}
